### ISSUE TITLE
sqlcoder-7b.Q5_K_M.gguf is missing 

### ISSUE THREAD

**Issue by MohamedMaghrby** [yonitjio/exploring-odoo#1]
hii , Yonitjio 

kindly , can you provide a source for sqlcoder-7b.Q5_K_M.gguf ?

**Comment by yonitjio** [comment]
> hii , Yonitjio 
> 
> kindly , can you provide a source for sqlcoder-7b.Q5_K_M.gguf ?

Hi, you can get it from  TheBloke at huggingface: https://huggingface.co/TheBloke/sqlcoder-7B-GGUF
